// try {
//     console.log(hello);
// } catch (error) {
//     console.log(error.name);
//     console.log(error.message);
//     console.log(error.stack);
// }

// const customErr = new ReferenceError("kya hi error hai");
// customErr.name = "Hitesh";
// customErr.message = "Student at sout";

// try {
//     // console.log(hell);
//     throw new Error;
    
// } catch (error) {
//     console.log(customErr);
    
// }

// throw new ReferenceError("mast error")
try {
    console.log("hello");
    
} catch (error) {
    console.log(error);
    
} finally {
    console.log("mai toh chalunga");
    
}